// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateTaskApiDrgTaskCreatePostData, CreateTaskApiDrgTaskCreatePostErrors, CreateTaskApiDrgTaskCreatePostResponses, GenerateDocApiAgentGenerateDocPostData, GenerateDocApiAgentGenerateDocPostErrors, GenerateDocApiAgentGenerateDocPostResponses, GetTaskListApiDrgTaskListGetData, GetTaskListApiDrgTaskListGetResponses, GetTaskProgressApiDrgTaskTaskIdProgressStepGetData, GetTaskProgressApiDrgTaskTaskIdProgressStepGetErrors, GetTaskProgressApiDrgTaskTaskIdProgressStepGetResponses, GetTaskResultApiDrgTaskResultTaskIdGetData, GetTaskResultApiDrgTaskResultTaskIdGetErrors, GetTaskResultApiDrgTaskResultTaskIdGetResponses, GetTaskResultStreamApiDrgTaskResultTaskIdStreamGetData, GetTaskResultStreamApiDrgTaskResultTaskIdStreamGetErrors, GetTaskResultStreamApiDrgTaskResultTaskIdStreamGetResponses, GetTaskStatusApiDrgTaskStatusGetData, GetTaskStatusApiDrgTaskStatusGetErrors, GetTaskStatusApiDrgTaskStatusGetResponses, ListDocTypesApiAgentDocTypesGetData, ListDocTypesApiAgentDocTypesGetResponses, LoginApiAuthLoginPostData, LoginApiAuthLoginPostErrors, LoginApiAuthLoginPostResponses, LogoutApiAuthLogoutPostData, LogoutApiAuthLogoutPostResponses, RefreshAccessTokenApiAuthRefreshPostData, RefreshAccessTokenApiAuthRefreshPostErrors, RefreshAccessTokenApiAuthRefreshPostResponses, RootGetData, RootGetResponses, ServeSpaFullPathGetData, ServeSpaFullPathGetErrors, ServeSpaFullPathGetResponses, SignupApiAuthSignupPostData, SignupApiAuthSignupPostErrors, SignupApiAuthSignupPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Signup
 *
 * sign up a new user, return a JWT token (no need to login again)
 */
export const signupApiAuthSignupPost = <ThrowOnError extends boolean = false>(options: Options<SignupApiAuthSignupPostData, ThrowOnError>) => (options.client ?? client).post<SignupApiAuthSignupPostResponses, SignupApiAuthSignupPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/auth/signup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login
 *
 * Login user and return JWT tokens
 */
export const loginApiAuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginApiAuthLoginPostData, ThrowOnError>) => (options.client ?? client).post<LoginApiAuthLoginPostResponses, LoginApiAuthLoginPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Refresh Access Token
 *
 * Use Refresh Token to get a new Access Token if access token expired
 */
export const refreshAccessTokenApiAuthRefreshPost = <ThrowOnError extends boolean = false>(options?: Options<RefreshAccessTokenApiAuthRefreshPostData, ThrowOnError>) => (options?.client ?? client).post<RefreshAccessTokenApiAuthRefreshPostResponses, RefreshAccessTokenApiAuthRefreshPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/auth/refresh',
    ...options
});

/**
 * Logout
 *
 * Logout user by clearing the Refresh Token
 */
export const logoutApiAuthLogoutPost = <ThrowOnError extends boolean = false>(options?: Options<LogoutApiAuthLogoutPostData, ThrowOnError>) => (options?.client ?? client).post<LogoutApiAuthLogoutPostResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/auth/logout',
    ...options
});

/**
 * Generate Doc
 *
 * 生成技术文档。
 *
 * 接收前端提示词 + 可选的需求文件，按 doc_type 生成 Markdown 文档。
 * 若未上传 source_file，默认使用 requirement.md。
 */
export const generateDocApiAgentGenerateDocPost = <ThrowOnError extends boolean = false>(options?: Options<GenerateDocApiAgentGenerateDocPostData, ThrowOnError>) => (options?.client ?? client).post<GenerateDocApiAgentGenerateDocPostResponses, GenerateDocApiAgentGenerateDocPostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/api/agent/generate-doc',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});

/**
 * List Doc Types
 *
 * 返回支持的文档类型。
 */
export const listDocTypesApiAgentDocTypesGet = <ThrowOnError extends boolean = false>(options?: Options<ListDocTypesApiAgentDocTypesGetData, ThrowOnError>) => (options?.client ?? client).get<ListDocTypesApiAgentDocTypesGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/agent/doc-types',
    ...options
});

/**
 * Create Task
 *
 * create a new task
 * return the task id
 */
export const createTaskApiDrgTaskCreatePost = <ThrowOnError extends boolean = false>(options: Options<CreateTaskApiDrgTaskCreatePostData, ThrowOnError>) => (options.client ?? client).post<CreateTaskApiDrgTaskCreatePostResponses, CreateTaskApiDrgTaskCreatePostErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/drg/task/create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Task List
 *
 * get the task list of the current user
 */
export const getTaskListApiDrgTaskListGet = <ThrowOnError extends boolean = false>(options?: Options<GetTaskListApiDrgTaskListGetData, ThrowOnError>) => (options?.client ?? client).get<GetTaskListApiDrgTaskListGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/drg/task/list',
    ...options
});

/**
 * Get Task Status
 *
 * get the status of the tasks
 */
export const getTaskStatusApiDrgTaskStatusGet = <ThrowOnError extends boolean = false>(options: Options<GetTaskStatusApiDrgTaskStatusGetData, ThrowOnError>) => (options.client ?? client).get<GetTaskStatusApiDrgTaskStatusGetResponses, GetTaskStatusApiDrgTaskStatusGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/drg/task/status',
    ...options
});

/**
 * Get Task Result Stream
 *
 * get the result of the task in streaming format
 */
export const getTaskResultStreamApiDrgTaskResultTaskIdStreamGet = <ThrowOnError extends boolean = false>(options: Options<GetTaskResultStreamApiDrgTaskResultTaskIdStreamGetData, ThrowOnError>) => (options.client ?? client).get<GetTaskResultStreamApiDrgTaskResultTaskIdStreamGetResponses, GetTaskResultStreamApiDrgTaskResultTaskIdStreamGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/drg/task/result/{task_id}/stream',
    ...options
});

/**
 * Get Task Result
 *
 * get the result of the task
 */
export const getTaskResultApiDrgTaskResultTaskIdGet = <ThrowOnError extends boolean = false>(options: Options<GetTaskResultApiDrgTaskResultTaskIdGetData, ThrowOnError>) => (options.client ?? client).get<GetTaskResultApiDrgTaskResultTaskIdGetResponses, GetTaskResultApiDrgTaskResultTaskIdGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/drg/task/result/{task_id}',
    ...options
});

/**
 * Get Task Progress
 *
 * Get the progress of a task at a specific step.
 * if the task has been completed, the is_completed field will be True.
 */
export const getTaskProgressApiDrgTaskTaskIdProgressStepGet = <ThrowOnError extends boolean = false>(options: Options<GetTaskProgressApiDrgTaskTaskIdProgressStepGetData, ThrowOnError>) => (options.client ?? client).get<GetTaskProgressApiDrgTaskTaskIdProgressStepGetResponses, GetTaskProgressApiDrgTaskTaskIdProgressStepGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/drg/task/{task_id}/progress/{step}',
    ...options
});

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/',
    ...options
});

/**
 * Serve Spa
 */
export const serveSpaFullPathGet = <ThrowOnError extends boolean = false>(options: Options<ServeSpaFullPathGetData, ThrowOnError>) => (options.client ?? client).get<ServeSpaFullPathGetResponses, ServeSpaFullPathGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/{full_path}',
    ...options
});
