// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { HelloApiHelloGetData, HelloApiHelloGetResponses, RootGetData, RootGetResponses, ServeSpaFullPathGetData, ServeSpaFullPathGetErrors, ServeSpaFullPathGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/',
    ...options
});

/**
 * Hello
 */
export const helloApiHelloGet = <ThrowOnError extends boolean = false>(options?: Options<HelloApiHelloGetData, ThrowOnError>) => (options?.client ?? client).get<HelloApiHelloGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/hello',
    ...options
});

/**
 * Serve Spa
 */
export const serveSpaFullPathGet = <ThrowOnError extends boolean = false>(options: Options<ServeSpaFullPathGetData, ThrowOnError>) => (options.client ?? client).get<ServeSpaFullPathGetResponses, ServeSpaFullPathGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/{full_path}',
    ...options
});
