// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HelloApiHelloGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/hello/';
};

export type HelloApiHelloGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ServeSpaFullPathGetData = {
    body?: never;
    path: {
        /**
         * Full Path
         */
        full_path: string;
    };
    query?: never;
    url: '/{full_path}';
};

export type ServeSpaFullPathGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ServeSpaFullPathGetError = ServeSpaFullPathGetErrors[keyof ServeSpaFullPathGetErrors];

export type ServeSpaFullPathGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
